---
- name: Installing tomcat9 and tomcat9-admin on all the nodes
  hosts: webservers
  tasks:
   - name: Installing tomcat9
     apt: 
      name: tomcat9
      state: present
      update_cache: yes
   - name: Installing tomcat9-admin
     apt:
      name: tomcat9-admin
      state: present
      update_cache: no
   - name: Copying tomcat-users.xml
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: Change the port 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      dest: /etc/tomcat9/server.xml
   - name: Pausing the tomcat9
     pause:
      minutes: 1
   - name: Restarting tomcat9
     service:
      name: tomcat9
      state: restarted
   - name: Check the URL on server1
     uri:
      url: http://172.31.22.1:9090
      status_code: 200
   - name: Check the URL on server2
     uri: 
     url: http://172.31.16.232:9090
      status_code: 200

 
